name: 'keel webhook deploy'
description: 'Calls keel.sh webhook to deploy docker image'
branding:
  icon: server
  color: green
inputs:
  image:
    description: 'image url to push'
    required: true
  keelBaseUrl:
    description: 'base url of keel webhook, http://keel.yourdomain.com:9300'
    required: true
  tag:
    description: 'tag to push'
    required: false
    default: "latest"
  auth:
    description: 'user:password for basic auth'
    required: true
  insecure:
    type: boolean
    required: false
    default: false

runs:
steps:
  - name: insecure update
    using: 'docker'
    image: 'docker://curlimages/curl:latest'
    if: ${{ inputs.insecure && inputs.insecure != false }}
    args:
      - '--silent'
      - '--show-error'
      - '--fail'
      - '-u'
      - '${{ inputs.auth }}'
      - '-X'
      - 'POST'
      - '-d'
      - '{"name": "${{ inputs.image }}", "tag": "${{ inputs.tag }}"}'
      - '${{ inputs.keelBaseUrl }}/v1/webhooks/native'
  - name: update  
    using: 'docker'
    image: 'docker://curlimages/curl:latest'
    if: ${{ inputs.insecure && inputs.insecure == false }}
    args:
      - '--silent'
      - '--show-error'
      - '--fail'
      - '-u'
      - '${{ inputs.auth }}'
      - '-X'
      - 'POST'
      - '-d'
      - '{"name": "${{ inputs.image }}", "tag": "${{ inputs.tag }}"}'
      - '${{ inputs.keelBaseUrl }}/v1/webhooks/native'
